# Generated by Django 5.2.5 on 2025-10-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simkarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('tarif', models.CharField(max_length=100, verbose_name='tarif nomi')),
                ('tarif_narxi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tarif narxi (so‘m)')),
                ('tavsif', models.TextField(blank=True, verbose_name='tavsif')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='simkartalar/icons/', verbose_name='ikonka')),
                ('simkarta_turi', models.CharField(choices=[('prepaid', 'Oldindan to‘lov (Prepaid)'), ('postpaid', 'Keyin to‘lov (Postpaid)'), ('esim', 'Elektron SIM (eSIM)')], max_length=20, verbose_name='simkarta turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simkarta',
                'verbose_name_plural': 'Simkartalar',
                'db_table': 'simkartalar',
                'ordering': ['name'],
            },
        ),
    ]
