# Generated by Django 5.2.5 on 2025-11-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilapp', '0002_simkarta_name_en_simkarta_name_ru_simkarta_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simkarta',
            name='link',
            field=models.URLField(blank=True, verbose_name='maʼlumotlar sahifasi'),
        ),
    ]
