# Generated by Django 5.2.5 on 2025-10-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='address_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='address_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_type_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_type_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='documents_note_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='documents_note_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='documents_note_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_type_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_type_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='p2poffer',
            name='commission_note_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='p2poffer',
            name='commission_note_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='p2poffer',
            name='commission_note_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='p2poffer',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p2poffer',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p2poffer',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
