# Generated by Django 5.2.5 on 2025-11-12 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_app_name_en_app_name_ru_app_name_uz_bank_address_en_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLClickStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('last_clicked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'url_click_stat',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'field_name'], name='url_click_s_content_0c1587_idx'), models.Index(fields=['updated_at'], name='url_click_s_updated_01875a_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name'), name='unique_click_stat_per_field')],
            },
        ),
    ]
