# Generated by Django 5.2.5 on 2025-10-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SugurtaCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='kompaniya nomi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('company_about', models.TextField(blank=True, verbose_name='kompaniya haqida')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('image', models.ImageField(blank=True, null=True, upload_to='insurance/companies/', verbose_name='rasm / logo')),
            ],
            options={
                'verbose_name': 'Sug‘urta kompaniyasi',
                'verbose_name_plural': 'Sug‘urta kompaniyalari',
                'db_table': 'sugurta_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sugurta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='mahsulot nomi')),
                ('sugurta_turi', models.CharField(choices=[('osago', 'Majburiy avtoulov (OSAGO)'), ('kasko', 'KASKO'), ('travel', 'Sayohat sug‘urtasi'), ('health', 'Sog‘liq sug‘urtasi'), ('property', 'Mulk sug‘urtasi'), ('life', 'Hayot sug‘urtasi'), ('other', 'Boshqa')], max_length=20, verbose_name='sug‘urta turi')),
                ('shaxs_roli', models.CharField(choices=[('individual', 'Jismoniy shaxs'), ('company', 'Yuridik shaxs')], max_length=20, verbose_name='shaxs roli')),
                ('link', models.URLField(blank=True, verbose_name='havola')),
                ('image', models.ImageField(blank=True, null=True, upload_to='insurance/products/', verbose_name='rasm')),
                ('sugurta_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugurtalar', to='sugurtaapp.sugurtacompany', verbose_name='sug‘urta kompaniyasi')),
            ],
            options={
                'verbose_name': 'Sug‘urta',
                'verbose_name_plural': 'Sug‘urtalar',
                'db_table': 'sugurta',
                'ordering': ['sugurta_company__name', 'name'],
                'unique_together': {('sugurta_company', 'name')},
            },
        ),
    ]
