# Generated by Django 5.2.5 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugurtaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sugurta',
            unique_together={('sugurta_company', 'name')},
        ),
        migrations.AddField(
            model_name='sugurta',
            name='name_en',
            field=models.CharField(max_length=180, null=True, verbose_name='mahsulot nomi'),
        ),
        migrations.AddField(
            model_name='sugurta',
            name='name_ru',
            field=models.CharField(max_length=180, null=True, verbose_name='mahsulot nomi'),
        ),
        migrations.AddField(
            model_name='sugurta',
            name='name_uz',
            field=models.CharField(max_length=180, null=True, verbose_name='mahsulot nomi'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='company_about_en',
            field=models.TextField(blank=True, null=True, verbose_name='kompaniya haqida'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='company_about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='kompaniya haqida'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='company_about_uz',
            field=models.TextField(blank=True, null=True, verbose_name='kompaniya haqida'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='sugurtacompany',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='kompaniya nomi'),
        ),
        migrations.AlterUniqueTogether(
            name='sugurta',
            unique_together={('sugurta_company', 'name'), ('sugurta_company', 'name_en'), ('sugurta_company', 'name_ru'), ('sugurta_company', 'name_uz')},
        ),
    ]
