# Generated by Django 5.2.5 on 2025-10-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetProvayder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('tarif', models.CharField(max_length=150, verbose_name='tarif nomi')),
                ('tarif_narxi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='tarif narxi')),
                ('tavsifi', models.TextField(blank=True, verbose_name='tavsif')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='provayderlar/icons/', verbose_name='ikon')),
            ],
            options={
                'verbose_name': 'Internet provayder',
                'verbose_name_plural': 'Internet provayderlar',
                'db_table': 'internet_provayderlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qurilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('model', models.CharField(blank=True, max_length=150, verbose_name='model')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='narxi')),
                ('tavsifi', models.TextField(blank=True, verbose_name='tavsif')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='qurilmalar/icons/', verbose_name='ikon')),
                ('internet_provayder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qurilmalar', to='provayderapp.internetprovayder', verbose_name='internet provayder')),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'db_table': 'qurilmalar',
                'ordering': ['internet_provayder__name', 'name'],
            },
        ),
    ]
