# Generated by Django 5.2.5 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provayderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetprovayder',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='internetprovayder',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='internetprovayder',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='internetprovayder',
            name='tarif_en',
            field=models.CharField(max_length=150, null=True, verbose_name='tarif nomi'),
        ),
        migrations.AddField(
            model_name='internetprovayder',
            name='tarif_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='tarif nomi'),
        ),
        migrations.AddField(
            model_name='internetprovayder',
            name='tarif_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='tarif nomi'),
        ),
        migrations.AddField(
            model_name='internetprovayder',
            name='tavsifi_en',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='internetprovayder',
            name='tavsifi_ru',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='internetprovayder',
            name='tavsifi_uz',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='model_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='model_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='model_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='tavsifi_en',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='tavsifi_ru',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='qurilma',
            name='tavsifi_uz',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
    ]
