# Generated by Django 5.2.5 on 2025-10-24 11:25

import apps.talimapp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'fanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('web_sayt', models.URLField(blank=True, verbose_name='web-sayt')),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('tashkil_yili', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), apps.talimapp.models.max_value_current_year], verbose_name='tashkil topgan yili')),
                ('desc', models.TextField(blank=True, verbose_name='tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='universitetlar/')),
            ],
            options={
                'verbose_name': 'Universitet',
                'verbose_name_plural': 'Universitetlar',
                'db_table': 'universitetlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='XususiyMaktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('web_sayt', models.URLField(blank=True, verbose_name='web-sayt')),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('tashkil_yili', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), apps.talimapp.models.max_value_current_year], verbose_name='tashkil topgan yili')),
                ('mudir', models.CharField(blank=True, max_length=200, verbose_name='rahbar (mudir)')),
                ('desc', models.TextField(blank=True, verbose_name='tavsif')),
            ],
            options={
                'verbose_name': 'Xususiy maktab',
                'verbose_name_plural': 'Xususiy maktablar',
                'db_table': 'xususiy_maktablar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('dekan', models.CharField(blank=True, max_length=200, verbose_name='dekan')),
                ('telefon', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('tashkil_yili', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), apps.talimapp.models.max_value_current_year], verbose_name='tashkil yili')),
                ('desc', models.TextField(blank=True, verbose_name='tavsif')),
                ('universitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakultetlar', to='talimapp.universitet')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'db_table': 'fakultetlar',
                'ordering': ['universitet__name', 'name'],
                'unique_together': {('universitet', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UniverYonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='yo‘nalish nomi')),
                ('talim_turi', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki'), ('online', 'Masofaviy (onlayn)')], default='kunduzgi', max_length=20, verbose_name="ta'lim turi")),
                ('talim_muddati_y', models.PositiveSmallIntegerField(help_text='yillarda', validators=[django.core.validators.MinValueValidator(1)], verbose_name="ta'lim muddati (yil)")),
                ('kontrakt_summasi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='kontrakt summasi')),
                ('grant_mavjudmi', models.BooleanField(default=False, verbose_name='grant mavjudmi')),
                ('desc', models.TextField(blank=True, verbose_name='tavsif')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='talimapp.fakultet')),
            ],
            options={
                'verbose_name': 'Universitet yo‘nalishi',
                'verbose_name_plural': 'Universitet yo‘nalishlari',
                'db_table': 'univer_yonalishlar',
                'ordering': ['fakultet__universitet__name', 'fakultet__name', 'name'],
                'unique_together': {('fakultet', 'name', 'talim_turi')},
            },
        ),
        migrations.CreateModel(
            name='MaktabYonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='yo‘nalish nomi')),
                ('talim_muddati_o', models.PositiveSmallIntegerField(help_text='oylarda', validators=[django.core.validators.MinValueValidator(1)], verbose_name="ta'lim muddati (oy)")),
                ('oqish_summasi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='o‘qish summasi')),
                ('grant_mavjudmi', models.BooleanField(default=False, verbose_name='grant mavjudmi')),
                ('desc', models.TextField(blank=True, verbose_name='tavsif')),
                ('fanlar', models.ManyToManyField(blank=True, related_name='maktab_yonalishlari', to='talimapp.fan')),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='talimapp.xususiymaktab')),
            ],
            options={
                'verbose_name': 'Maktab yo‘nalishi',
                'verbose_name_plural': 'Maktab yo‘nalishlari',
                'db_table': 'maktab_yonalishlar',
                'ordering': ['maktab__name', 'name'],
                'unique_together': {('maktab', 'name')},
            },
        ),
    ]
