# Generated by Django 5.2.5 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talimapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fakultet',
            unique_together={('universitet', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='maktabyonalish',
            unique_together={('maktab', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='univeryonalish',
            unique_together={('fakultet', 'name', 'talim_turi')},
        ),
        migrations.AddField(
            model_name='fakultet',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='fan',
            name='name_en',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='fan nomi'),
        ),
        migrations.AddField(
            model_name='fan',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='fan nomi'),
        ),
        migrations.AddField(
            model_name='fan',
            name='name_uz',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='fan nomi'),
        ),
        migrations.AddField(
            model_name='maktabyonalish',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='maktabyonalish',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='maktabyonalish',
            name='desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='maktabyonalish',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='yo‘nalish nomi'),
        ),
        migrations.AddField(
            model_name='maktabyonalish',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='yo‘nalish nomi'),
        ),
        migrations.AddField(
            model_name='maktabyonalish',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='yo‘nalish nomi'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='universitet',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='univeryonalish',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='univeryonalish',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='univeryonalish',
            name='desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='univeryonalish',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='yo‘nalish nomi'),
        ),
        migrations.AddField(
            model_name='univeryonalish',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='yo‘nalish nomi'),
        ),
        migrations.AddField(
            model_name='univeryonalish',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='yo‘nalish nomi'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='xususiymaktab',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AlterUniqueTogether(
            name='fakultet',
            unique_together={('universitet', 'name'), ('universitet', 'name_en'), ('universitet', 'name_ru'), ('universitet', 'name_uz')},
        ),
        migrations.AlterUniqueTogether(
            name='maktabyonalish',
            unique_together={('maktab', 'name'), ('maktab', 'name_en'), ('maktab', 'name_ru'), ('maktab', 'name_uz')},
        ),
        migrations.AlterUniqueTogether(
            name='univeryonalish',
            unique_together={('fakultet', 'name', 'talim_turi'), ('fakultet', 'name_en', 'talim_turi'), ('fakultet', 'name_ru', 'talim_turi'), ('fakultet', 'name_uz', 'talim_turi')},
        ),
    ]
